/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _guessRouteRouteImport } from './routes/__guess/route'
import { Route as _authedRouteRouteImport } from './routes/__authed/route'
import { Route as _authedIndexRouteImport } from './routes/__authed/index'
import { Route as _guessSignUpRouteImport } from './routes/__guess/sign-up'
import { Route as _guessSignInRouteImport } from './routes/__guess/sign-in'
import { Route as _authedCreateRouteImport } from './routes/__authed/create'
import { Route as _authedViewPromptIdRouteImport } from './routes/__authed/view.$promptId'
import { Route as _authedEditPromptIdRouteImport } from './routes/__authed/edit.$promptId'

const _guessRouteRoute = _guessRouteRouteImport.update({
  id: '/__guess',
  getParentRoute: () => rootRouteImport,
} as any)
const _authedRouteRoute = _authedRouteRouteImport.update({
  id: '/__authed',
  getParentRoute: () => rootRouteImport,
} as any)
const _authedIndexRoute = _authedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _authedRouteRoute,
} as any)
const _guessSignUpRoute = _guessSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => _guessRouteRoute,
} as any)
const _guessSignInRoute = _guessSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => _guessRouteRoute,
} as any)
const _authedCreateRoute = _authedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => _authedRouteRoute,
} as any)
const _authedViewPromptIdRoute = _authedViewPromptIdRouteImport.update({
  id: '/view/$promptId',
  path: '/view/$promptId',
  getParentRoute: () => _authedRouteRoute,
} as any)
const _authedEditPromptIdRoute = _authedEditPromptIdRouteImport.update({
  id: '/edit/$promptId',
  path: '/edit/$promptId',
  getParentRoute: () => _authedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof _authedIndexRoute
  '/create': typeof _authedCreateRoute
  '/sign-in': typeof _guessSignInRoute
  '/sign-up': typeof _guessSignUpRoute
  '/edit/$promptId': typeof _authedEditPromptIdRoute
  '/view/$promptId': typeof _authedViewPromptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof _authedIndexRoute
  '/create': typeof _authedCreateRoute
  '/sign-in': typeof _guessSignInRoute
  '/sign-up': typeof _guessSignUpRoute
  '/edit/$promptId': typeof _authedEditPromptIdRoute
  '/view/$promptId': typeof _authedViewPromptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__authed': typeof _authedRouteRouteWithChildren
  '/__guess': typeof _guessRouteRouteWithChildren
  '/__authed/create': typeof _authedCreateRoute
  '/__guess/sign-in': typeof _guessSignInRoute
  '/__guess/sign-up': typeof _guessSignUpRoute
  '/__authed/': typeof _authedIndexRoute
  '/__authed/edit/$promptId': typeof _authedEditPromptIdRoute
  '/__authed/view/$promptId': typeof _authedViewPromptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/sign-in'
    | '/sign-up'
    | '/edit/$promptId'
    | '/view/$promptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/sign-in'
    | '/sign-up'
    | '/edit/$promptId'
    | '/view/$promptId'
  id:
    | '__root__'
    | '/__authed'
    | '/__guess'
    | '/__authed/create'
    | '/__guess/sign-in'
    | '/__guess/sign-up'
    | '/__authed/'
    | '/__authed/edit/$promptId'
    | '/__authed/view/$promptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authedRouteRoute: typeof _authedRouteRouteWithChildren
  _guessRouteRoute: typeof _guessRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__guess': {
      id: '/__guess'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _guessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authed': {
      id: '/__authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authed/': {
      id: '/__authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _authedIndexRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/__guess/sign-up': {
      id: '/__guess/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof _guessSignUpRouteImport
      parentRoute: typeof _guessRouteRoute
    }
    '/__guess/sign-in': {
      id: '/__guess/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof _guessSignInRouteImport
      parentRoute: typeof _guessRouteRoute
    }
    '/__authed/create': {
      id: '/__authed/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof _authedCreateRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/__authed/view/$promptId': {
      id: '/__authed/view/$promptId'
      path: '/view/$promptId'
      fullPath: '/view/$promptId'
      preLoaderRoute: typeof _authedViewPromptIdRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/__authed/edit/$promptId': {
      id: '/__authed/edit/$promptId'
      path: '/edit/$promptId'
      fullPath: '/edit/$promptId'
      preLoaderRoute: typeof _authedEditPromptIdRouteImport
      parentRoute: typeof _authedRouteRoute
    }
  }
}

interface _authedRouteRouteChildren {
  _authedCreateRoute: typeof _authedCreateRoute
  _authedIndexRoute: typeof _authedIndexRoute
  _authedEditPromptIdRoute: typeof _authedEditPromptIdRoute
  _authedViewPromptIdRoute: typeof _authedViewPromptIdRoute
}

const _authedRouteRouteChildren: _authedRouteRouteChildren = {
  _authedCreateRoute: _authedCreateRoute,
  _authedIndexRoute: _authedIndexRoute,
  _authedEditPromptIdRoute: _authedEditPromptIdRoute,
  _authedViewPromptIdRoute: _authedViewPromptIdRoute,
}

const _authedRouteRouteWithChildren = _authedRouteRoute._addFileChildren(
  _authedRouteRouteChildren,
)

interface _guessRouteRouteChildren {
  _guessSignInRoute: typeof _guessSignInRoute
  _guessSignUpRoute: typeof _guessSignUpRoute
}

const _guessRouteRouteChildren: _guessRouteRouteChildren = {
  _guessSignInRoute: _guessSignInRoute,
  _guessSignUpRoute: _guessSignUpRoute,
}

const _guessRouteRouteWithChildren = _guessRouteRoute._addFileChildren(
  _guessRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _authedRouteRoute: _authedRouteRouteWithChildren,
  _guessRouteRoute: _guessRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
